stages:
- prepare
- build
- test

variables:
  DOCKER_FILE: Dockerfile
  DOCKER_TAG: latest
  DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}
  GIT_SUBMODULE_STRATEGY: normal
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1

.prepare:docker: &prepare_docker
  stage: prepare
  image:
    name: docker
  before_script:
    - docker version
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - docker build -f ${DOCKER_FILE} -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
    - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  tags:
    - docker

prepare:docker:
  <<: *prepare_docker

build:demo:
  stage: build
  image: ${DOCKER_IMAGE}:${DOCKER_TAG}
  script:
    - if [ -d "$HOME/tmp_libhermit-rs" ]; then rm -rf $HOME/tmp_libhermit-rs; fi
    - mkdir $HOME/tmp_libhermit-rs
    - shopt -s dotglob nullglob && mv ./* $HOME/tmp_libhermit-rs
    # If for some reason target exists (due to a bad cache) then delete it.
    - if [ -d "$HOME/tmp_libhermit-rs/target" ]; then rm -rf $HOME/tmp_libhermit-rs/target; fi
    - git clone https://github.com/hermitcore/rusty-hermit.git
    - cd rusty-hermit
    - echo "rusty-hermit at commit $(git rev-parse HEAD)"
    # Ensure that libhermit-rs is empty - This shouldn't be necessary since we don't initialize the submodules
    # But let's do it anyway to be safe
    - if [ -d "libhermit-rs" ]; then rm -rf libhermit-rs; fi
    - mkdir libhermit-rs
    - shopt -s dotglob nullglob && mv $HOME/tmp_libhermit-rs/* libhermit-rs/.
    - cargo build -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-hermit --package rusty_demo
    - cargo build -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-hermit --package rusty_demo --release
  artifacts:
    paths:
      - rusty-hermit/target/x86_64-unknown-hermit/debug/rusty_demo
      - rusty-hermit/target/x86_64-unknown-hermit/release/rusty_demo

test:integration:
  stage: test
  image: ${DOCKER_IMAGE}:${DOCKER_TAG}
  script:
    - lscpu
    - kvm-ok
    - python3 --version
    - HERMIT_LOG_LEVEL_FILTER=Debug cargo test --test '*' --no-fail-fast -Z build-std=core,alloc 
        -Z build-std-features=compiler-builtins-mem --no-default-features --features=pci,acpi 
        --target targets/x86_64-unknown-none-hermitkernel.json -- --veryverbose
    - HERMIT_LOG_LEVEL_FILTER=Debug cargo test --test '*' --no-fail-fast -Z build-std=core,alloc 
        -Z build-std-features=compiler-builtins-mem --no-default-features --features=pci,acpi 
        --target targets/x86_64-unknown-none-hermitkernel.json -- --num_cores 2
        --veryverbose
  tags:
    - privileged

test:uhyve:
   stage: test
   dependencies:
     - build:demo
   image: ${DOCKER_IMAGE}:${DOCKER_TAG}
   script:
     - lscpu
     - kvm-ok
     - uhyve -v -c 1 rusty-hermit/target/x86_64-unknown-hermit/debug/rusty_demo
     - uhyve -v -c 2 rusty-hermit/target/x86_64-unknown-hermit/debug/rusty_demo
     - uhyve -v -c 1 rusty-hermit/target/x86_64-unknown-hermit/release/rusty_demo
     - uhyve -v -c 2 rusty-hermit/target/x86_64-unknown-hermit/release/rusty_demo
   tags:
     - privileged

test:qemu:
   stage: test
   dependencies:
     - build:demo
   image: ${DOCKER_IMAGE}:${DOCKER_TAG}
   script:
     - lscpu
     - kvm-ok
     - qemu-system-x86_64 -smp 1
        -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand
        -device isa-debug-exit,iobase=0xf4,iosize=0x04
        -display none -m 64M -serial stdio -enable-kvm
        -kernel /usr/local/bin/rusty-loader
        -initrd rusty-hermit/target/x86_64-unknown-hermit/debug/rusty_demo
     - qemu-system-x86_64 -smp 2
        -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand
        -device isa-debug-exit,iobase=0xf4,iosize=0x04
        -display none -m 64M -serial stdio -enable-kvm
        -kernel /usr/local/bin/rusty-loader
        -initrd rusty-hermit/target/x86_64-unknown-hermit/debug/rusty_demo
     - qemu-system-x86_64 -smp 1
        -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand
        -device isa-debug-exit,iobase=0xf4,iosize=0x04
        -display none -m 64M -serial stdio -enable-kvm
        -kernel /usr/local/bin/rusty-loader
        -initrd rusty-hermit/target/x86_64-unknown-hermit/release/rusty_demo
     - qemu-system-x86_64 -smp 2
        -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand
        -device isa-debug-exit,iobase=0xf4,iosize=0x04
        -display none -m 64M -serial stdio -enable-kvm
        -kernel /usr/local/bin/rusty-loader
        -initrd rusty-hermit/target/x86_64-unknown-hermit/release/rusty_demo
   tags:
     - privileged
