[default]
locale = "en-us"
extend-ignore-identifiers-re = [
    "IST",
    "ist",
    "parm",
    "sie",
]

[default.extend-identifiers]
Acces = "Acces"
BARs = "BARs"
BMCR_ANE = "BMCR_ANE"
consts = "consts"
DT_WHT = "DT_WHT"
DtWht = "DtWht"
RCR_AER = "RCR_AER"
