[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
goblin = { version = "0.8", default-features = false, features = ["archive", "elf32", "elf64", "std"] }
llvm-tools = "0.1"
sysinfo = "0.30"
ureq = "2"
wait-timeout = "0.2"
xshell = "0.2"
