[unstable]
# Keep in sync with CI!
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-unknown-none-hermitkernel"
rustflags = [
  "-Zmutable-noalias=no"
]

[target.x86_64-unknown-none-hermitkernel]
runner = "tests/hermit_test_runner.py"
